language: java
branches:
  only:
  - develop

install: ""

script: "cd /usr/src/ && mvn clean verify"

services:
  - docker

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: develop
